webtalk_init -webtalk_dir /home/fiee/Nutstore Files/pytorchtest/FPGA_project_reference/TheBigProject/TheBigProject.sim/sim_1/behav/xsim/xsim.dir/ButtonSim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May  9 22:50:47 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aa42b3a2-779e-4b98-b8bf-4a076ca6c846" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8979ec7cb1f84925a3b893383450791d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.001 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115584_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3157636963 -regid "" -xml /home/fiee/Nutstore Files/pytorchtest/FPGA_project_reference/TheBigProject/TheBigProject.sim/sim_1/behav/xsim/xsim.dir/ButtonSim_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/fiee/Nutstore Files/pytorchtest/FPGA_project_reference/TheBigProject/TheBigProject.sim/sim_1/behav/xsim/xsim.dir/ButtonSim_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/fiee/Nutstore Files/pytorchtest/FPGA_project_reference/TheBigProject/TheBigProject.sim/sim_1/behav/xsim/xsim.dir/ButtonSim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
