# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/Tetris_Basys3.cache/wt} [current_project]
set_property parent.project_path {C:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/Tetris_Basys3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/Tetris_Basys3.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/source/tetris_main.v}
  {C:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/source/tetris_seg.v}
  {C:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/source/tetris_vga2.v}
  {C:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/source/Tetris_top.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/source/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Teaching_Materials/CEE-325 Fall 2017/Project 2017/Tetris_Basys3/source/Basys3_Master.xdc}}]


synth_design -top Tetris_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Tetris_top.dcp

catch { report_utilization -file Tetris_top_utilization_synth.rpt -pb Tetris_top_utilization_synth.pb }
